config/routes.rb
Rails.application.routes.draw do
  get 'category/index'
  get 'category/show'
  resources :pages

  get '/static/:permalink', to: 'pages#permalink', as: 'permalink'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: %i[index show] do
    collection do
      get 'search_results'
    end
  end



  # post 'cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  # delete 'cart/:id', to: 'products#delete_from_cart', as: 'delete_to_cart'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'products#index'
  root to: 'products#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_and_belongs_to_many :categories

  has_one_attached :image
  paginates_per 9

  def fullsize
    image.variant(resize: '900x900!')
  end

  def medium
    image.variant(resize: '600x600!')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_categories

  private

  def set_categories
    @cats = Category.all
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base

  http_basic_authenticate_with name: "admin", password: "password", except: :permalink

  def permalink
    @page = Page.find_by_permalink(params[:permalink])
    if @page
      render :show
    else
      redirect_to root_path
    end
  end

  private
    def page_params
      params.require(:page).permit(:title, :content, :permalink)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :load_cart


  def index
    @products = Product.page params[:page]
  end

  def show
    @product = Product.find(params[:id])
  end

  def search_results
    @query = params[:query]
    @category = params[:category]
    if @category == ""
      @products = Product.where('name LIKE ?', "%#{@query}%")
    else
      @products = Product.joins(:categories).where('products.name LIKE ? and categories.id LIKE ?', "%#{@query}%", "#{@category}")
    end
  end

  # @products = Product.joins(:categories).where('products.name LIKE ? and categories.id LIKE ?', "%#{@query}%", "#{@category}")
  # def add_to_cart
  #   id = params[:id].to_i
  #   session[:cart] << id unless session[:cart].include?(id)
  #   redirect_to root_path
  # end

  # def delete_from_cart
  #   id = params[:id].to_i
  #   session[:cart].delete(id)
  #   redirect_to root_path
  # end

  # private

  # def load_cart
  #   @cart = Product.find(session[:cart])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThreadRiverThrift</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>

  <body>
    <header>
      <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="https://bulma.io">
            <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
          </a>

          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <%= link_to 'Home', root_path, :class => "navbar-item" %>
            <%= link_to 'About Us', permalink_path(permalink: 'about-us'), :class => "navbar-item" %>
            <%= link_to 'Contact', permalink_path(permalink: 'contact'), :class => "navbar-item" %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                Categories
              </a>

              <div class="navbar-dropdown">
                <% @cats.each do |category| %>
                  <%= link_to category.name, search_results_products_path(query: "", category: category.id), :class => "navbar-item" %>
                <% end %>
              </div>
            </div>
          </div>
          <%= form_with(url: search_results_products_path, method: "get", local: true) do %>
            <%= label_tag(:query, "Search for:") %>
            <%= text_field_tag(:query) %>
            <%= select_tag :category, options_from_collection_for_select(@cats, 'id', 'name'), include_blank: "All" %>
            <%= submit_tag("Search") %>
          <% end %>
        </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-primary">
                  <strong>Sign up</strong>
                </a>
                <a class="button is-light">
                  Log in
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <section class="section">
      <%= yield %>
    </section>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">
  <%= @page.title %>
</h1>

<p>
  <%= @page.content %>
</p>

app/views/products/_product.html.erb
<div class="column is-one-third">
  <%= link_to product_path(product.id) do %>
    <div class="card product">
      <div class="card-content">
        <p class="title is-4"><%= product.name %></p>
        <p><%= image_tag product.medium %></p>
        <ul>
          <li><strong>Price: </strong><%= product.price %></li>
          <li><strong>Size: </strong><%= product.size %></li>
          <li><strong>Quantity: </strong><%= product.quantity %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<h1 class="title">All Products</h1>
<%= paginate @products %>
<div class="columns is-multiline">
  <%= render @products %>
</div>

app/views/products/search_results.html.erb
<p>Your search for <%= @query %> returned <%= pluralize(@products.size, 'results') %></p>

<section class="section">
<div class="columns is-multiline">
<%= render @products %>
</div>
</section>

app/views/products/show.html.erb
<section class="section">
<div class="columns is-centered">
  <div class="column is-two-fifths">
    <%= image_tag @product.fullsize %>
  </div>
  <div class="column is-two-fifths">
    <section class="section">
      <h1 class="title is-centered"><%= @product.name %></h1>
    </section>
    <section class="section">
      <p class="is-size-5"><strong>Size: <%= @product.size %></strong></p>
      <br>
      <p class="is-size-5"><strong>Qty: <%= @product.quantity %></strong></p>
      <br>
      <p class="is-size-5"><strong>Price: <%= @product.price %></strong></p>
    </section>
    <section class="section">
      <button class="button is-medium is-info">Add To Cart</button>
    </section>
  </div>
</div>
</section>